export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST';
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS';
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL';
export const ADMIN_LIST_RESET = 'ADMIN_LIST_FAIL';

export const ADMIN_DETAILS_REQUEST = 'ADMIN_DETAILS_REQUEST';
export const ADMIN_DETAILS_SUCCESS = 'ADMIN_DETAILS_SUCCESS';
export const ADMIN_DETAILS_FAIL = 'ADMIN_DETAILS_FAIL';
export const ADMIN_DETAILS_RESET = 'ADMIN_DETAILS_RESET';

export const ADMIN_DELETE_REQUEST = 'ADMIN_DELETE_REQUEST';
export const ADMIN_DELETE_SUCCESS = 'ADMIN_DELETE_SUCCESS';
export const ADMIN_DELETE_FAIL = 'ADMIN_DELETE_FAIL';

export const ADMIN_CREATE_REQUEST = 'ADMIN_CREATE_REQUEST';
export const ADMIN_CREATE_SUCCESS = 'ADMIN_CREATE_SUCCESS';
export const ADMIN_CREATE_FAIL = 'ADMIN_CREATE_FAIL';
export const ADMIN_CREATE_RESET = 'ADMIN_CREATE_RESET';

export const ADMIN_UPDATE_REQUEST = 'ADMIN_UPDATE_REQUEST';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN_UPDATE_SUCCESS';
export const ADMIN_UPDATE_FAIL = 'ADMIN_UPDATE_FAIL';
export const ADMIN_UPDATE_RESET = 'ADMIN_UPDATE_RESET';


export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGIN_SUCESS = 'ADMIN_LOGIN_SUCESS';
export const ADMIN_LOGOUT = 'ADMIN_LOGIN';


export const ADMIN_FORGET_PASSWORD_REQUEST = 'ADMIN_FORGET_PASSWORD_REQUEST';
export const ADMIN_FORGET_PASSWORD_FAIL = 'ADMIN_FORGET_PASSWORD_FAIL';
export const ADMIN_FORGET_PASSWORD_SUCESS = 'ADMIN_FORGET_PASSWORD_SUCESS';

export const ADMIN_PASSWORD_CHANGE_REQUEST = 'ADMIN_PASSWORD_CHANGE_REQUEST';
export const ADMIN_PASSWORD_CHANGE_SUCCESS = 'ADMIN_PASSWORD_CHANGE_SUCCESS';
export const ADMIN_PASSWORD_CHANGE_FAIL = 'ADMIN_PASSWORD_CHANGE_FAIL';
export const ADMIN_PASSWORD_CHANGE_RESET = 'ADMIN_PASSWORD_CHANGE_RESET';