export const DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST";
export const DOCTOR_LIST_SUCCESS = "DOCTOR_LIST_SUCCESS";
export const DOCTOR_LIST_FAIL = "DOCTOR_LIST_FAIL";
export const DOCTOR_LIST_RESET = "DOCTOR_LIST_RESET";

export const DOCTOR_SIGNUP_REQUEST = "DOCTOR_SIGNUP_REQUEST";
export const DOCTOR_SIGNUP_SUCCESS = "DOCTOR_SIGNUP_SUCCESS";
export const DOCTOR_SIGNUP_FAIL = "DOCTOR_SIGNUP_FAIL";
export const DOCTOR_SIGNUP_RESET = "DOCTOR_SIGNUP_RESET";

export const DOCTOR_SIGNUP_LIST_REQUEST = "DOCTOR_SIGNUP_LIST_REQUEST";
export const DOCTOR_SIGNUP_LIST_SUCCESS = "DOCTOR_SIGNUP_LIST_SUCCESS";
export const DOCTOR_SIGNUP_LIST_FAIL = "DOCTOR_SIGNUP_LIST_FAIL";
export const DOCTOR_SIGNUP_LIST_RESET = "DOCTOR_SIGNUP_LIST_RESET";

export const DOCTOR_SIGNUP_APPROVED_REQUEST = "DOCTOR_SIGNUP_APPROVED_REQUEST";
export const DOCTOR_SIGNUP_APPROVED_SUCCESS = "DOCTOR_SIGNUP_APPROVED_SUCCESS";
export const DOCTOR_SIGNUP_APPROVED_FAIL = "DOCTOR_SIGNUP_APPROVED_FAIL";
export const DOCTOR_SIGNUP_APPROVED_RESET = "DOCTOR_SIGNUP_APPROVED_RESET";

export const DOCTOR_SIGNUP_APPROVED_LIST_REQUEST =
  "DOCTOR_SIGNUP_APPROVED_LIST_REQUEST";
export const DOCTOR_SIGNUP_APPROVED_LIST_SUCCESS =
  "DOCTOR_SIGNUP_APPROVED_LIST_SUCCESS";
export const DOCTOR_SIGNUP_APPROVED_LIST_FAIL =
  "DOCTOR_SIGNUP_APPROVED_LIST_FAIL";
export const DOCTOR_SIGNUP_APPROVED_LIST_RESET =
  "DOCTOR_SIGNUP_APPROVED_LIST_RESET";

  export const DOCTOR_SIGNUP_NOT_APPROVED_LIST_REQUEST =
    "DOCTOR_SIGNUP_NOT_APPROVED_LIST_REQUEST";
  export const DOCTOR_SIGNUP_NOT_APPROVED_LIST_SUCCESS =
    "DOCTOR_SIGNUP_NOT_APPROVED_LIST_SUCCESS";
  export const DOCTOR_SIGNUP_NOT_APPROVED_LIST_FAIL =
    "DOCTOR_SIGNUP_NOT_APPROVED_LIST_FAIL";
  export const DOCTOR_SIGNUP_NOT_APPROVED_LIST_RESET =
    "DOCTOR_SIGNUP_NOT_APPROVED_LIST_RESET";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";
export const DOCTOR_DETAILS_RESET = "DOCTOR_DETAILS_RESET";

export const DOCTOR_DELETE_REQUEST = "DOCTOR_DELETE_REQUEST";
export const DOCTOR_DELETE_SUCCESS = "DOCTOR_DELETE_SUCCESS";
export const DOCTOR_DELETE_FAIL = "DOCTOR_DELETE_FAIL";

export const DOCTOR_CREATE_REQUEST = "DOCTOR_CREATE_REQUEST";
export const DOCTOR_CREATE_SUCCESS = "DOCTOR_CREATE_SUCCESS";
export const DOCTOR_CREATE_FAIL = "DOCTOR_CREATE_FAIL";
export const DOCTOR_CREATE_RESET = "DOCTOR_CREATE_RESET";

export const DOCTOR_UPDATE_REQUEST = "DOCTOR_UPDATE_REQUEST";
export const DOCTOR_UPDATE_SUCCESS = "DOCTOR_UPDATE_SUCCESS";
export const DOCTOR_UPDATE_FAIL = "DOCTOR_UPDATE_FAIL";
export const DOCTOR_UPDATE_RESET = "DOCTOR_UPDATE_RESET";

export const DOCTOR_LOGIN_REQUEST = "DOCTOR_LOGIN_REQUEST";
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL";
export const DOCTOR_LOGIN_SUCESS = "DOCTOR_LOGIN_SUCESS";
export const DOCTOR_LOGOUT = "DOCTOR_LOGIN_LOGOUT";

export const DOCTOR_UPLOAD_PROFILE_REQUEST = "DOCTOR_UPLOAD_PROFILE_REQUEST";
export const DOCTOR_UPLOAD_PROFILE_SUCCESS = "DOCTOR_UPLOAD_PROFILE_SUCCESS";
export const DOCTOR_UPLOAD_PROFILE_FAIL = "DOCTOR_UPLOAD_PROFILE_FAIL";
export const DOCTOR_UPLOAD_PROFILE_RESET = "DOCTOR_UPLOAD_PROFILE_RESET";

export const DOCTOR_ADD_NUMBER_REQUEST = "DOCTOR_ADD_NUMBER_REQUEST";
export const DOCTOR_ADD_NUMBER_SUCCESS = "DOCTOR_ADD_NUMBER_SUCCESS";
export const DOCTOR_ADD_NUMBER_FAIL = "DOCTOR_ADD_NUMBER_FAIL";
export const DOCTOR_ADD_NUMBER_RESET = "DOCTOR_ADD_NUMBER_RESET";

export const DOCTOR_DELETE_NUMBER_REQUEST = "DOCTOR_DELETE_NUMBER_REQUEST";
export const DOCTOR_DELETE_NUMBER_SUCCESS = "DOCTOR_DELETE_NUMBER_SUCCESS";
export const DOCTOR_DELETE_NUMBER_FAIL = "DOCTOR_DELETE_NUMBER_FAIL";
export const DOCTOR_DELETE_NUMBER_RESET = "DOCTOR_DELETE_NUMBER_RESET";

export const DOCTOR_ADD_VIDEO_REQUEST = "DOCTOR_ADD_VIDEO_REQUEST";
export const DOCTOR_ADD_VIDEO_SUCCESS = "DOCTOR_ADD_VIDEO_SUCCESS";
export const DOCTOR_ADD_VIDEO_FAIL = "DOCTOR_ADD_VIDEO_FAIL";
export const DOCTOR_ADD_VIDEO_RESET = "DOCTOR_ADD_VIDEO_RESET";

export const DOCTOR_DELETE_VIDEO_REQUEST = "DOCTOR_DELETE_VIDEO_REQUEST";
export const DOCTOR_DELETE_VIDEO_SUCCESS = "DOCTOR_DELETE_VIDEO_SUCCESS";
export const DOCTOR_DELETE_VIDEO_FAIL = "DOCTOR_DELETE_VIDEO_FAIL";
export const DOCTOR_DELETE_VIDEO_RESET = "DOCTOR_DELETE_VIDEO_RESET";

export const DOCTOR_ADD_EDUCATION_REQUEST = "DOCTOR_ADD_EDUCATION_REQUEST";
export const DOCTOR_ADD_EDUCATION_SUCCESS = "DOCTOR_ADD_EDUCATION_SUCCESS";
export const DOCTOR_ADD_EDUCATION_FAIL = "DOCTOR_ADD_EDUCATION_FAIL";
export const DOCTOR_ADD_EDUCATION_RESET = "DOCTOR_ADD_EDUCATION_RESET";

export const DOCTOR_DELETE_EDUCATION_REQUEST =
  "DOCTOR_DELETE_EDUCATION_REQUEST";
export const DOCTOR_DELETE_EDUCATION_SUCCESS =
  "DOCTOR_DELETE_EDUCATION_SUCCESS";
export const DOCTOR_DELETE_EDUCATION_FAIL = "DOCTOR_DELETE_EDUCATION_FAIL";
export const DOCTOR_DELETE_EDUCATION_RESET = "DOCTOR_DELETE_EDUCATION_RESET";

export const DOCTOR_ADD_TAG_REQUEST = "DOCTOR_ADD_TAG_REQUEST";
export const DOCTOR_ADD_TAG_SUCCESS = "DOCTOR_ADD_TAG_SUCCESS";
export const DOCTOR_ADD_TAG_FAIL = "DOCTOR_ADD_TAG_FAIL";
export const DOCTOR_ADD_TAG_RESET = "DOCTOR_ADD_TAG_RESET";

export const DOCTOR_ADD_TIME_REQUEST = "DOCTOR_ADD_TIME_REQUEST";
export const DOCTOR_ADD_TIME_SUCCESS = "DOCTOR_ADD_TIME_SUCCESS";
export const DOCTOR_ADD_TIME_FAIL = "DOCTOR_ADD_TIME_FAIL";
export const DOCTOR_ADD_TIME_RESET = "DOCTOR_ADD_TIME_RESET";

export const DOCTOR_DELETE_TAG_REQUEST = "DOCTOR_DELETE_TAG_REQUEST";
export const DOCTOR_DELETE_TAG_SUCCESS = "DOCTOR_DELETE_TAG_SUCCESS";
export const DOCTOR_DELETE_TAG_FAIL = "DOCTOR_DELETE_TAG_FAIL";
export const DOCTOR_DELETE_TAG_RESET = "DOCTOR_DELETE_TAG_RESET";

export const DOCTOR_ADD_PROFILE_REQUEST = "DOCTOR_ADD_PROFILE_REQUEST";
export const DOCTOR_ADD_PROFILE_SUCCESS = "DOCTOR_ADD_PROFILE_SUCCESS";
export const DOCTOR_ADD_PROFILE_FAIL = "DOCTOR_ADD_PROFILE_FAIL";

export const DOCTOR_FORGOT_PASSWORD_REQUEST = "DOCTOR_FORGOT_PASSWORD_REQUEST";
export const DOCTOR_FORGOT_PASSWORD_SUCCESS = "DOCTOR_FORGOT_PASSWORD_SUCCESS";
export const DOCTOR_FORGOT_PASSWORD_FAIL = "DOCTOR_FORGOT_PASSWORD_FAIL";
export const DOCTOR_FORGOT_PASSWORD_RESET = "DOCTOR_FORGOT_PASSWORD_RESET";

export const DOCTOR_PASSWORD_CHANGE_REQUEST = "DOCTOR_PASSWORD_CHANGE_REQUEST";
export const DOCTOR_PASSWORD_CHANGE_SUCCESS = "DOCTOR_PASSWORD_CHANGE_SUCCESS";
export const DOCTOR_PASSWORD_CHANGE_FAIL = "DOCTOR_PASSWORD_CHANGE_FAIL";
export const DOCTOR_PASSWORD_CHANGE_RESET = "DOCTOR_PASSWORD_CHANGE_RESET";
