export const PRESCRIPTION_CREATE_REQUEST = 'PRESCRIPTION_CREATE_REQUEST';
export const PRESCRIPTION_CREATE_SUCCESS = 'PRESCRIPTION_CREATE_SUCCESS';
export const PRESCRIPTION_CREATE_FAIL = 'PRESCRIPTION_CREATE_FAIL';
export const PRESCRIPTION_CREATE_RESET = 'PRESCRIPTION_CREATE_RESET';


export const PRESCRIPTION_SEND_REQUEST = 'PRESCRIPTION_SEND_REQUEST';
export const PRESCRIPTION_SEND_SUCCESS = 'PRESCRIPTION_SEND_SUCCESS';
export const PRESCRIPTION_SEND_FAIL = 'PRESCRIPTION_SEND_FAIL';
export const PRESCRIPTION_SEND_RESET = 'PRESCRIPTION_SEND_RESET';
