export const SUPERADMIN_LOGIN_REQUEST = 'SUPERADMIN_LOGIN_REQUEST';
export const SUPERADMIN_LOGIN_FAIL = 'SUPERADMIN_LOGIN_FAIL';
export const SUPERADMIN_LOGIN_SUCESS = 'SUPERADMIN_LOGIN_SUCESS';
export const SUPERADMIN_LOGOUT = 'SUPERADMIN_LOGIN_LOGOUT';

export const SUPERADMIN_REGISTER_REQUEST = 'SUPERADMIN_REGISTER_REQUEST';
export const SUPERADMIN_REGISTER_FAIL = 'SUPERADMIN_REGISTER_FAIL';
export const SUPERADMIN_REGISTER_SUCESS = 'SUPERADMIN_REGISTER_SUCESS';

export const SUPERADMIN_DETAILS_REQUEST = 'SUPERADMIN_DETAILS_REQUEST';
export const SUPERADMIN_DETAILS_FAIL = 'SUPERADMIN_DETAILS_FAIL';
export const SUPERADMIN_DETAILS_SUCESS = 'SUPERADMIN_DETAILS_SUCESS';

export const SUPERADMIN_UPDATE_PROFILE_REQUEST = 'SUPERADMIN_UPDATE_PROFILE_REQUEST';
export const SUPERADMIN_UPDATE_PROFILE_FAIL = 'SUPERADMIN_UPDATE_PROFILE_FAIL';
export const SUPERADMIN_UPDATE_PROFILE_SUCESS = 'SUPERADMIN_UPDATE_PROFILE_SUCESS';
